# Generated by Django 3.0.5 on 2020-07-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LastSaved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voie', models.CharField(max_length=20)),
                ('nbr_voiture', models.IntegerField(default=0)),
                ('nbr_personne', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MoyPer40Scd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voie', models.CharField(max_length=20)),
                ('moy_voiture', models.FloatField()),
                ('moy_personne', models.FloatField()),
                ('debit', models.FloatField()),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voie', models.CharField(max_length=20)),
                ('nbr_voiture', models.IntegerField(default=0)),
                ('nbr_personne', models.IntegerField(default=0)),
            ],
        ),
    ]
