# Generated by Django 3.0.5 on 2020-07-05 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0)),
                ('t_accidents', models.FloatField()),
                ('t_deaths', models.FloatField()),
                ('t_injured', models.FloatField()),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewAccident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('governorate', models.CharField(max_length=25)),
                ('n_dead', models.FloatField()),
                ('n_injured', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='AccidentReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('governorate', models.CharField(max_length=20)),
                ('accidents', models.FloatField()),
                ('dead', models.FloatField()),
                ('injured', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='accidents.Accident')),
            ],
        ),
    ]
