# Generated by Django 3.0.5 on 2020-07-05 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import leads.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cin', models.IntegerField()),
                ('objet', models.CharField(blank=True, max_length=500)),
                ('fil', models.FileField(blank=True, null=True, upload_to=leads.models.upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande',
                'verbose_name_plural': 'Demandes',
            },
        ),
    ]
