# Generated by Django 3.0.5 on 2020-07-05 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carfour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mode', models.SmallIntegerField(default=2)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tricolor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=50)),
                ('red_seconds', models.SmallIntegerField(default=40)),
                ('green_seconds', models.SmallIntegerField(default=40)),
                ('yellow_seconds', models.SmallIntegerField(default=5)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('tricolors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tricolors', to='tricolor.Carfour')),
            ],
        ),
    ]
